<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2010 rel. 3 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:clitype="clitype" xmlns:clm54217="urn:un:unece:uncefact:codelist:specification:54217:2001" xmlns:clm5639="urn:un:unece:uncefact:codelist:specification:5639:1988" xmlns:clm66411="urn:un:unece:uncefact:codelist:specification:66411:2001" xmlns:clmIANAMIMEMediaType="urn:un:unece:uncefact:codelist:specification:IANAMIMEMediaType:2003" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:n1="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:qdt="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2" xmlns:udt="urn:un:unece:uncefact:data:specification:UnqualifiedDataTypesSchemaModule:2" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com" exclude-result-prefixes="cac cbc ccts clitype clm54217 clm5639 clm66411 clmIANAMIMEMediaType ext fn iso4217 ix java link n1 qdt udt xbrldi xbrli xlink xs xsd xsi altova">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:decimal-format name="format1" grouping-separator=" " decimal-separator=","/>
	<xsl:template match="/">
		<html>
			<head>
				<title>
					<xsl:text> </xsl:text>
				</title>
				<meta http-equiv="X-UA-Compatible" content="IE=7"/>
				<style type="text/css">
					<xsl:comment>* {
                        font-size:medium;
                        font-weight:500;
                    }
                    * {
                        font-size:small;
                    }
                    </xsl:comment>
				</style>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:0.6in; margin-right:0.6in; margin-top:0.79in; margin-bottom:0.79in } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body>
				<table border="0" width="100%">
					<xsl:variable name="altova:CurrContextGrid_0B234788" select="."/>
					<tbody>
						<tr style="height:0.16in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PartyName">
													<xsl:for-each select="cbc:Name">
														<span style="font-size:medium; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="width:4.03in; " valign="bottom">
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
							</td>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; ">
								<span style="font-size:x-large; ">
									<xsl:text>Faktura</xsl:text>
								</span>
							</td>
							<td style="width:0.04in; "/>
							<td style="width:1.80in; " align="right"/>
						</tr>
						<tr style="height:0.03in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:StreetName">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:BuildingNumber">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="width:4.03in; ">
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<br/>
							</td>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; ">
								<span>
									<xsl:text>Fakturanummer</xsl:text>
								</span>
							</td>
							<td style="width:0.04in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="width:1.80in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cbc:ID">
											<xsl:apply-templates/>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.01in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:Postbox">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; ">
								<span>
									<xsl:text>Fakturadato</xsl:text>
								</span>
							</td>
							<td style="width:0.04in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="width:1.80in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cbc:IssueDate">
											<span>
												<xsl:variable name="altova:seqContentStrings">
													<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
													<xsl:text>. </xsl:text>
													<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
													<xsl:text>. </xsl:text>
													<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
												</xsl:variable>
												<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
												<xsl:value-of select="$sContent"/>
											</span>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.01in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:PostalZone">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:CityName">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="width:4.03in; ">
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
							</td>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; ">
								<span>
									<xsl:text>Forfallsdato</xsl:text>
								</span>
							</td>
							<td style="width:0.04in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="width:1.80in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:PaymentMeans">
											<xsl:for-each select="cbc:PaymentDueDate">
												<span>
													<xsl:variable name="altova:seqContentStrings">
														<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
														<xsl:text>. </xsl:text>
														<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
														<xsl:text>. </xsl:text>
														<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
													</xsl:variable>
													<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
													<xsl:value-of select="$sContent"/>
												</span>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.04in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; "/>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; ">
								<span>
									<xsl:text>Kundenummer</xsl:text>
								</span>
							</td>
							<td style="width:0.04in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="width:1.80in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PartyIdentification">
													<xsl:for-each select="cbc:ID">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.09in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; ">
								<span>
									<xsl:text>Org.-/Bedriftsnummer:&#160; </xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PartyLegalEntity">
													<xsl:for-each select="cbc:CompanyID">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; "/>
							<td style="width:0.04in; "/>
							<td style="width:1.80in; " align="right"/>
						</tr>
						<tr style="height:0.01in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; ">
								<br/>
							</td>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; ">
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
							</td>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; ">
								<span>
									<xsl:text>Kontonr.</xsl:text>
								</span>
							</td>
							<td style="width:0.04in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="width:1.80in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:PaymentMeans">
											<xsl:for-each select="cac:PayeeFinancialAccount">
												<xsl:for-each select="cbc:ID">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.01in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; "/>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; ">
								<span>
									<xsl:text>Valuta</xsl:text>
								</span>
							</td>
							<td style="width:0.04in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="width:1.80in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cbc:DocumentCurrencyCode">
											<xsl:apply-templates/>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.09in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; "/>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; "/>
							<td style="width:0.04in; "/>
							<td style="width:1.80in; " align="right"/>
						</tr>
						<tr style="height:0.01in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PartyName">
													<xsl:for-each select="cbc:Name">
														<span style="font-size:medium; ">
															<xsl:apply-templates/>
														</span>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; ">
								<span>
									<xsl:text>Deres ref.</xsl:text>
								</span>
							</td>
							<td style="width:0.04in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="width:1.80in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:Contact">
													<xsl:for-each select="cbc:ID">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.01in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:StreetName">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:BuildingNumber">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; ">
								<span>
									<xsl:text>Vår ref.</xsl:text>
								</span>
							</td>
							<td style="width:0.04in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="width:1.80in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingSupplierParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:Contact">
													<xsl:for-each select="cbc:ID">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.01in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:PostalZone">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PostalAddress">
													<xsl:for-each select="cbc:CityName">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
							</td>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; ">
								<span>
									<xsl:text>Ordrenr.</xsl:text>
								</span>
							</td>
							<td style="width:0.04in; ">
								<span>
									<xsl:text>:</xsl:text>
								</span>
							</td>
							<td style="width:1.80in; " align="left">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:OrderReference">
											<xsl:for-each select="cbc:ID">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
						</tr>
						<tr style="height:0.06in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; "/>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; "/>
							<td style="width:0.04in; "/>
							<td style="width:1.80in; " align="right"/>
						</tr>
						<tr style="height:0.09in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; ">
								<span>
									<xsl:text>Org.-/Bedriftsnummer:&#160; </xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:AccountingCustomerParty">
											<xsl:for-each select="cac:Party">
												<xsl:for-each select="cac:PartyLegalEntity">
													<xsl:for-each select="cbc:CompanyID">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; "/>
							<td style="width:0.04in; "/>
							<td style="width:1.80in; " align="right"/>
						</tr>
						<tr style="height:0.14in; ">
							<td style="width:0.30in; "/>
							<td style="width:2.95in; "/>
							<td style="width:4.03in; "/>
							<td style="width:0.01in; "/>
							<td style="width:1.67in; "/>
							<td style="width:1.09in; "/>
							<td style="width:0.04in; "/>
							<td style="width:1.80in; "/>
						</tr>
					</tbody>
				</table>
				<table border="0" width="100%">
					<xsl:variable name="altova:CurrContextGrid_0D92CA70" select="."/>
					<tbody>
						<tr>
							<td style="width:0.48in; "/>
							<td style="width:1.17in; ">
								<span>
									<xsl:text>Leveringsadresse:</xsl:text>
								</span>
							</td>
							<td style="width:7.65in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:Delivery">
											<xsl:for-each select="cac:DeliveryLocation">
												<xsl:for-each select="cac:Address">
													<xsl:for-each select="cbc:StreetName">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:Delivery">
											<xsl:for-each select="cac:DeliveryLocation">
												<xsl:for-each select="cac:Address">
													<xsl:for-each select="cbc:BuildingNumber">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>, </xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:Delivery">
											<xsl:for-each select="cac:DeliveryLocation">
												<xsl:for-each select="cac:Address">
													<xsl:for-each select="cbc:PostalZone">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160;</xsl:text>
								</span>
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:Delivery">
											<xsl:for-each select="cac:DeliveryLocation">
												<xsl:for-each select="cac:Address">
													<xsl:for-each select="cbc:CityName">
														<xsl:apply-templates/>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
								<span>
									<xsl:text>&#160; </xsl:text>
								</span>
							</td>
							<td style="width:7.65in; "/>
						</tr>
						<tr style="height:0.10in; ">
							<td style="width:0.48in; "/>
							<td style="width:1.17in; ">
								<span>
									<xsl:text>Leveringsdato:</xsl:text>
								</span>
							</td>
							<td style="width:7.65in; ">
								<xsl:for-each select="$XML">
									<xsl:for-each select="n1:Invoice">
										<xsl:for-each select="cac:Delivery">
											<xsl:for-each select="cbc:ActualDeliveryDate">
												<span>
													<xsl:variable name="altova:seqContentStrings">
														<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
														<xsl:text>. </xsl:text>
														<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
														<xsl:text>. </xsl:text>
														<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
													</xsl:variable>
													<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
													<xsl:value-of select="$sContent"/>
												</span>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</td>
							<td style="width:7.65in; "/>
						</tr>
					</tbody>
				</table>
				<span>
					<xsl:text>&#160; </xsl:text>
				</span>
                <div style="margin-left: 5px;font-size:medium;font-weight:400;">
                    <xsl:for-each select="$XML">
                        <xsl:for-each select="n1:Invoice">
                            <xsl:for-each select="cbc:Note">
                                <xsl:apply-templates/>
                            </xsl:for-each>
                        </xsl:for-each>
                    </xsl:for-each>
                </div>
				<table class="invoice_lines" style="margin-top: 1em;margin-left: 5px; border: 1px solid #CCC">
					<xsl:variable name="altova:CurrContextGrid_0D92D190" select="."/>
					<thead >
						<tr style="background-color:#e9ffe9;">
							<th style="width:1.07in; border-bottom: 1px solid #CCC " align="left">
								<span style="font-weight:bold; ">
									<xsl:text>Artikkelnr.</xsl:text>
								</span>
							</th>
							<th style="width:5.02in; border-bottom: 1px solid #CCC" align="left">
								<span style="font-weight:bold; ">
									<xsl:text> Beskrivelse</xsl:text>
								</span>
							</th>
							<th style="width:1in; border-bottom: 1px solid #CCC" align="left">
								<span style="font-weight:bold; ">
									<xsl:text> Kontering</xsl:text>
								</span>
							</th>
							<th style="width:1in; border-bottom: 1px solid #CCC" align="center">
								<span style="font-weight:bold; ">
									<xsl:text> Antall&#160; </xsl:text>
								</span>
							</th>
							<th style="width:1.02in; border-bottom: 1px solid #CCC" align="left">
								<span style="font-weight:bold; ">
									<xsl:text>Enhet</xsl:text>
								</span>
							</th>
							<th style="width:1in; border-bottom: 1px solid #CCC" align="center">
								<span style="font-weight:bold; ">
									<xsl:text>Ordreref.&#160; </xsl:text>
								</span>
							</th>
							<th style="width:1.70in; border-bottom: 1px solid #CCC" align="center">
								<span style="font-weight:bold; ">
									<xsl:text>MVA</xsl:text>
								</span>
							</th>
							<th style="width:1.32in; border-bottom: 1px solid #CCC" align="right">
								<span style="font-weight:bold; ">
									<xsl:text>Pris&#160;&#160; </xsl:text>
								</span>
							</th>
							<th style="width:1.43in; border-bottom: 1px solid #CCC" align="right">
								<span style="font-weight:bold; ">
									<xsl:text>Linjebeløp&#160; </xsl:text>
								</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<xsl:for-each select="$XML">
							<xsl:for-each select="n1:Invoice">
								<xsl:for-each select="cac:InvoiceLine">
									<tr>
										<td style="width:1.07in; ">
											<table border="0">
												<xsl:variable name="altova:CurrContextGrid_0D92DC70" select="."/>
												<tbody>
													<xsl:for-each select="cac:Item">
														<tr>
															<td>
																<xsl:for-each select="cac:SellersItemIdentification">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</td>
														</tr>
													</xsl:for-each>
												</tbody>
											</table>
										</td>
										<td style="width:5.02in; ">
											<table border="0">
												<xsl:variable name="altova:CurrContextGrid_0D92DDF0" select="."/>
												<tbody>
													<xsl:for-each select="cac:Item">
														<tr>
															<td>
																<xsl:for-each select="cbc:Name">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</td>
														</tr>
													</xsl:for-each>
												</tbody>
											</table>
										</td>
										<td style="width:1in; ">
											<table border="0">
												<xsl:variable name="altova:CurrContextGrid_0D92DF70" select="."/>
												<tbody>
													<tr>
														<td align="left">
															<xsl:for-each select="cbc:AccountingCost">
																<xsl:apply-templates/>
															</xsl:for-each>
														</td>
													</tr>
												</tbody>
											</table>
										</td>
										<td style="width:1in; " align="center">
											<xsl:for-each select="cbc:InvoicedQuantity">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td style="width:1.02in; " align="left">
											<table border="0">
												<xsl:variable name="altova:CurrContextGrid_0D92E150" select="."/>
												<tbody>
													<xsl:for-each select="cbc:InvoicedQuantity">
														<tr>
															<td align="left">
																<xsl:for-each select="@unitCode">
																	<xsl:if test=".=&quot;NAR&quot;">
																		<span>
																			<xsl:text>Artikler</xsl:text>
																		</span>
																	</xsl:if>
																	<xsl:if test=".=&quot;NMP&quot;">
																		<span>
																			<xsl:text>Pakker</xsl:text>
																		</span>
																	</xsl:if>
																	<xsl:if test=".=&quot;KGM&quot;">
																		<span>
																			<xsl:text>Kilo</xsl:text>
																		</span>
																	</xsl:if>
																	<xsl:if test=".=&quot;LTR&quot;">
																		<span>
																			<xsl:text>Liter</xsl:text>
																		</span>
																	</xsl:if>
																	<xsl:if test=".=&quot;LH&quot;">
																		<span>
																			<xsl:text>Arbeidstime</xsl:text>
																		</span>
																	</xsl:if>
																	<xsl:if test=".=&quot;WM&quot;">
																		<span>
																			<xsl:text>Arbeidsmåned</xsl:text>
																		</span>
																	</xsl:if>
																	<xsl:if test=".=&quot;MTR&quot;">
																		<span>
																			<xsl:text>Meter</xsl:text>
																		</span>
																	</xsl:if>
																	<xsl:if test=".=&quot;KWT&quot;">
																		<span>
																			<xsl:text>Kilowatt</xsl:text>
																		</span>
																	</xsl:if>
																	<xsl:if test=".=&quot;IE&quot;">
																		<span>
																			<xsl:text>Person</xsl:text>
																		</span>
																	</xsl:if>
																	<xsl:if test=".!=&quot;IE&quot;">
																		<xsl:if test=".!=&quot;KWT&quot;">
																			<xsl:if test=".!=&quot;LTR&quot;">
																				<xsl:if test=".!=&quot;NAR&quot;">
																					<xsl:if test=".!=&quot;LH&quot;">
																						<xsl:if test=".!=&quot;WM&quot;">
																							<xsl:if test=".!=&quot;LH&quot;">
																								<xsl:if test=".!=&quot;KGM&quot;">
																									<xsl:if test=".!=&quot;NMP&quot;">
																										<span>
																											<xsl:value-of select="string(.)"/>
																										</span>
																									</xsl:if>
																								</xsl:if>
																							</xsl:if>
																						</xsl:if>
																					</xsl:if>
																				</xsl:if>
																			</xsl:if>
																		</xsl:if>
																	</xsl:if>
																</xsl:for-each>
															</td>
														</tr>
													</xsl:for-each>
												</tbody>
											</table>
										</td>
										<td style="width:1in; " align="center">
											<xsl:for-each select="cac:OrderLineReference">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td style="width:1.70in; " align="center">
											<table border="0">
												<xsl:variable name="altova:CurrContextGrid_0D92E690" select="."/>
												<tbody>
													<xsl:for-each select="cac:Item">
														<xsl:for-each select="cac:ClassifiedTaxCategory">
															<tr>
																<td>
																	<xsl:for-each select="cbc:Percent">
																		<span>
																			<xsl:variable name="altova:seqContentStrings">
																				<xsl:value-of select="format-number(number(string(.)), '##0', 'format1')"/>
																			</xsl:variable>
																			<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																			<xsl:value-of select="$sContent"/>
																		</span>
																		<span>
																			<xsl:text> %</xsl:text>
																		</span>
																	</xsl:for-each>
																</td>
															</tr>
														</xsl:for-each>
													</xsl:for-each>
												</tbody>
											</table>
										</td>
										<td style="width:1.32in; " align="right">
											<table border="0">
												<xsl:variable name="altova:CurrContextGrid_0D92E870" select="."/>
												<tbody>
													<xsl:for-each select="cac:Price">
														<tr>
															<td align="right">
																<xsl:for-each select="cbc:PriceAmount">
																	<span>
																		<xsl:variable name="altova:seqContentStrings">
																			<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																		</xsl:variable>
																		<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																		<xsl:value-of select="$sContent"/>
																	</span>
																</xsl:for-each>
															</td>
														</tr>
													</xsl:for-each>
												</tbody>
											</table>
										</td>
										<td style="width:1.43in; " align="right">
											<table border="0">
												<xsl:variable name="altova:CurrContextGrid_0D92E9F0" select="."/>
												<tbody>
													<tr>
														<td align="right">
															<xsl:for-each select="cbc:LineExtensionAmount">
																<span>
																	<xsl:variable name="altova:seqContentStrings">
																		<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																	</xsl:variable>
																	<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																	<xsl:value-of select="$sContent"/>
																</span>
															</xsl:for-each>
														</td>
													</tr>
												</tbody>
											</table>
										</td>
									</tr>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</tbody>
				</table>
				<table border="0" width="100%">
					<xsl:variable name="altova:CurrContextGrid_0D92EB10" select="."/>
					<tbody>
						<tr>
							<td/>
							<td/>
							<td>
								<table border="0" width="100%">
									<xsl:variable name="altova:CurrContextGrid_0D92EDB0" select="."/>
									<tbody>
										<tr style="height:0.07in; ">
											<td style="width:7.23in; "/>
											<td style="width:3.82in; " align="right">
												<span>
													<xsl:text>Totalt linjebeløp før MVA</xsl:text>
												</span>
											</td>
											<td style="width:1.06in; " align="right">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:LegalMonetaryTotal">
															<xsl:for-each select="cbc:LineExtensionAmount">
																<span>
																	<xsl:variable name="altova:seqContentStrings">
																		<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																	</xsl:variable>
																	<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																	<xsl:value-of select="$sContent"/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
				<span>
					<xsl:text>&#160;&#160; </xsl:text>
				</span>
				<br/>
				<table border="0" width="100%">
					<xsl:variable name="altova:CurrContextGrid_0D92F110" select="."/>
					<tbody>
						<tr>
							<td style="width:4.40in; "/>
							<td style="width:10in; "/>
							<td style="width:4.98in; ">
								<table style="border:1px solid #CCC; spacing:0 padding:0">
									<xsl:variable name="altova:CurrContextGrid_0D92F3B0" select="."/>
									<thead>
										<tr style="background-color:#e9ffe9; ">
											<th style="width:1.24in; border-bottom: 1px solid #CCC " align="right">
												<span style="font-weight:bold; ">
													<xsl:text>MVA grunnlag</xsl:text>
												</span>
											</th>
											<th style="width:1.38in; border-bottom: 1px solid #CCC  " align="center">
												<span style="font-weight:bold; ">
													<xsl:text>MVA </xsl:text>
												</span>
											</th>
											<th style="width:1.32in; border-bottom: 1px solid #CCC " align="right">
												<span style="font-weight:bold; ">
													<xsl:text>MVA beløp</xsl:text>
												</span>
											</th>
										</tr>
									</thead>
									<tbody>
										<xsl:for-each select="$XML">
											<xsl:for-each select="n1:Invoice">
												<xsl:for-each select="cac:TaxTotal">
													<xsl:for-each select="cac:TaxSubtotal">
														<tr style="height:0.02in; ">
															<td style="width:1.24in; " align="right">
																<xsl:for-each select="cbc:TaxableAmount">
																	<span>
																		<xsl:variable name="altova:seqContentStrings">
																			<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																		</xsl:variable>
																		<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																		<xsl:value-of select="$sContent"/>
																	</span>
																</xsl:for-each>
															</td>
															<td style="width:1.38in; " align="center">
																<table border="0">
																	<xsl:variable name="altova:CurrContextGrid_0D92F830" select="."/>
																	<tbody>
																		<xsl:for-each select="cac:TaxCategory">
																			<tr>
																				<td align="center">
																					<xsl:for-each select="cbc:Percent">
																						<span>
																							<xsl:variable name="altova:seqContentStrings">
																								<xsl:value-of select="format-number(number(string(.)), '##0', 'format1')"/>
																							</xsl:variable>
																							<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																							<xsl:value-of select="$sContent"/>
																						</span>
																					</xsl:for-each>
																					<span>
																						<xsl:text> %</xsl:text>
																					</span>
																				</td>
																			</tr>
																		</xsl:for-each>
																	</tbody>
																</table>
															</td>
															<td style="width:1.32in; " align="right">
																<xsl:for-each select="cbc:TaxAmount">
																	<span>
																		<xsl:variable name="altova:seqContentStrings">
																			<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																		</xsl:variable>
																		<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																		<xsl:value-of select="$sContent"/>
																	</span>
																</xsl:for-each>
															</td>
														</tr>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
				<br/>
				<table border="0" width="100%">
					<xsl:variable name="altova:CurrContextGrid_0D92FA10" select="."/>
					<tbody>
						<tr>
							<td/>
							<td/>
							<td>
								<table border="0" width="100%">
									<xsl:variable name="altova:CurrContextGrid_0D92FCB0" select="."/>
									<tbody>
										<tr style="height:0.02in; ">
											<td style="width:11.42in; "/>
											<td style="width:1.46in; " align="left">
												<span>
													<xsl:text>Totalt MVA: </xsl:text>
												</span>
											</td>
											<td style="width:1.27in; " align="right">
												<span>
													<xsl:text>&#160;&#160;&#160;&#160; </xsl:text>
												</span>
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:TaxTotal">
															<xsl:for-each select="cbc:TaxAmount">
																<span>
																	<xsl:variable name="altova:seqContentStrings">
																		<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																	</xsl:variable>
																	<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																	<xsl:value-of select="$sContent"/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
										</tr>
										<tr style="height:0.02in; ">
											<td style="width:11.42in; "/>
											<td style="width:1.46in; " align="left">
												<span style="font-weight:bold; ">
													<xsl:text>Totalsum:</xsl:text>
												</span>
											</td>
											<td style="width:1.27in; " align="right">
												<span>
													<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
												</span>
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:LegalMonetaryTotal">
															<xsl:for-each select="cbc:PayableAmount">
																<span style="font-weight:bold; ">
																	<xsl:variable name="altova:seqContentStrings">
																		<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																	</xsl:variable>
																	<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																	<xsl:value-of select="$sContent"/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
				<br/>
				<table border="0" width="100%">
					<xsl:variable name="altova:CurrContextGrid_0D9301F0" select="."/>
					<tbody>
						<tr style="background-color:yellow; height:0.15in; ">
							<td>
								<table border="0" width="100%">
									<xsl:variable name="altova:CurrContextGrid_0D930310" select="."/>
									<tbody>
										<tr style="height:0.09in; ">
											<td style="width:0.43in; "/>
											<td style="width:6.44in; ">
												<span style="background-color:yellow; font-size:medium; font-weight:bold; ">
													<xsl:text>Kvittering</xsl:text>
												</span>
											</td>
											<td style="width:3.39in; "/>
											<td style="width:2.75in; ">
												<span style="font-size:small; ">
													<xsl:text>Beløp</xsl:text>
												</span>
											</td>
										</tr>
										<tr style="height:0.01in; ">
											<td style="width:0.43in; "/>
											<td style="width:6.44in; ">
												<span style="background-color:yellow; font-size:small; ">
													<xsl:text>Innbetalt til konto</xsl:text>
												</span>
												<span style="background-color:yellow; font-size:smaller; ">
													<xsl:text>&#160;</xsl:text>
												</span>
												<br/>
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:PaymentMeans">
															<xsl:for-each select="cac:PayeeFinancialAccount">
																<xsl:for-each select="cbc:ID">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="width:3.39in; ">
												<br/>
											</td>
											<td style="width:2.75in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:LegalMonetaryTotal">
															<xsl:for-each select="cbc:PayableAmount">
																<input style="width:1.46in; ">
																	<xsl:attribute name="value">
																		<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																	</xsl:attribute>
																</input>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td>
								<table style="background-color:white; " border="0" width="100%">
									<xsl:variable name="altova:CurrContextGrid_0D9309D0" select="."/>
									<tbody>
										<tr style="height:0.01in; ">
											<td style="background-color:white; width:0.43in; "/>
											<td style="background-color:white; width:3.04in; ">
												<span style="font-size:medium; ">
													<xsl:text>Betalingsinformasjon</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:2.03in; "/>
											<td style="background-color:white; width:2.82in; ">
												<span>
													<xsl:text>&#160;</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:2.80in; ">
												<span style="font-weight:bold; ">
													<xsl:text>GIRO</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:3in; ">
												<span style="font-size:small; ">
													<xsl:text>Betalingsfrist </xsl:text>
												</span>
												<br/>
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:PaymentMeans">
															<xsl:for-each select="cbc:PaymentDueDate">
																<input style="width:1.46in; ">
																	<xsl:attribute name="value">
																		<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																		<xsl:text>. </xsl:text>
																		<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																		<xsl:text>. </xsl:text>
																		<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																	</xsl:attribute>
																</input>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
										</tr>
										<tr>
											<td style="background-color:white; width:0.43in; "/>
											<td style="background-color:white; width:3.04in; ">
												<span>
													<xsl:text>Fakturanummer:</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:2.03in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cbc:ID">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; " align="right"/>
											<td style="background-color:white; width:3in; " valign="top"/>
										</tr>
										<tr>
											<td style="background-color:white; width:0.43in; "/>
											<td style="background-color:white; width:3.04in; ">
												<span>
													<xsl:text>Kundenummer:</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:2.03in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingCustomerParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PartyIdentification">
																	<xsl:for-each select="cbc:ID">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; " align="left">
												<span style="font-size:small; ">
													<xsl:text>Underskrift ved girering</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:3in; "/>
										</tr>
										<tr>
											<td style="background-color:white; width:0.43in; "/>
											<td style="background-color:white; width:3.04in; ">
												<span>
													<xsl:text>Fakturadato:</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:2.03in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cbc:IssueDate">
															<span>
																<xsl:variable name="altova:seqContentStrings">
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																	<xsl:text>. </xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																</xsl:variable>
																<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																<xsl:value-of select="$sContent"/>
															</span>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; " align="right"/>
											<td style="background-color:white; width:3in; "/>
										</tr>
										<tr>
											<td style="background-color:white; width:0.43in; "/>
											<td style="background-color:white; width:3.04in; ">
												<span>
													<xsl:text>Forfallsdato:</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:2.03in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:PaymentMeans">
															<xsl:for-each select="cbc:PaymentDueDate">
																<span>
																	<xsl:variable name="altova:seqContentStrings">
																		<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																		<xsl:text>. </xsl:text>
																		<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																		<xsl:text>. </xsl:text>
																		<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																	</xsl:variable>
																	<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																	<xsl:value-of select="$sContent"/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; " align="right"/>
											<td style="background-color:white; width:3in; "/>
										</tr>
										<tr style="height:0.16in; ">
											<td style="background-color:white; width:0.43in; "/>
											<td style="background-color:white; width:3.04in; "/>
											<td style="background-color:white; width:2.03in; "/>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; "/>
											<td style="background-color:white; width:3in; "/>
										</tr>
										<tr style="height:0.18in; ">
											<td style="background-color:white; width:0.43in; "/>
											<td style="background-color:white; width:3.04in; "/>
											<td style="background-color:white; width:2.03in; "/>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; "/>
											<td style="background-color:white; width:3in; "/>
										</tr>
										<tr style="height:0.18in; ">
											<td style="background-color:white; width:0.43in; "/>
											<td style="background-color:white; width:3.04in; "/>
											<td style="background-color:white; width:2.03in; "/>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; "/>
											<td style="background-color:white; width:3in; "/>
										</tr>
										<tr style="height:0.05in; ">
											<td style="background-color:white; width:0.43in; ">
												<span>
													<xsl:text>&#160;&#160;&#160;&#160;&#160; </xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:3.04in; ">
												<span style="font-size:medium; text-decoration:underline; ">
													<xsl:text>Betalt av</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:2.03in; "/>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; ">
												<span style="font-size:medium; text-decoration:underline; ">
													<xsl:text>Betalt til</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:3in; " valign="bottom"/>
										</tr>
										<tr style="height:0.01in; " valign="top">
											<td style="background-color:white; width:0.43in; ">
												<span>
													<xsl:text>&#160;&#160; </xsl:text>
												</span>
												<br/>
											</td>
											<td style="background-color:white; width:3.04in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingCustomerParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PartyName">
																	<xsl:for-each select="cbc:Name">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="background-color:white; width:2.03in; " valign="bottom">
												<br/>
											</td>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingSupplierParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PartyName">
																	<xsl:for-each select="cbc:Name">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="background-color:white; width:3in; " valign="top"/>
										</tr>
										<tr style="height:0.03in; " valign="top">
											<td style="background-color:white; width:0.43in; "/>
											<td style="background-color:white; width:3.04in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingCustomerParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PostalAddress">
																	<xsl:for-each select="cbc:StreetName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
												<span>
													<xsl:text>&#160;</xsl:text>
												</span>
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingCustomerParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PostalAddress">
																	<xsl:for-each select="cbc:BuildingNumber">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="background-color:white; width:2.03in; " valign="top"/>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingSupplierParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PostalAddress">
																	<xsl:for-each select="cbc:StreetName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
												<span>
													<xsl:text>&#160;</xsl:text>
												</span>
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingSupplierParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PostalAddress">
																	<xsl:for-each select="cbc:BuildingNumber">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="background-color:white; width:3in; "/>
										</tr>
										<tr style="height:0.03in; " valign="top">
											<td style="background-color:white; width:0.43in; "/>
											<td style="background-color:white; width:3.04in; ">
												<span>
													<xsl:text>&#160;</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:2.03in; "/>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingSupplierParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PostalAddress">
																	<xsl:for-each select="cbc:Postbox">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
												<span>
													<xsl:text>&#160;</xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:3in; "/>
										</tr>
										<tr style="height:0.03in; " valign="top">
											<td style="background-color:white; width:0.43in; " valign="bottom"/>
											<td style="background-color:white; width:3.04in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingCustomerParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PostalAddress">
																	<xsl:for-each select="cbc:PostalZone">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
												<span>
													<xsl:text>&#160;</xsl:text>
												</span>
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingCustomerParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PostalAddress">
																	<xsl:for-each select="cbc:CityName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="background-color:white; width:2.03in; " valign="bottom">
												<span>
													<xsl:text>&#160;&#160; </xsl:text>
												</span>
											</td>
											<td style="background-color:white; width:2.82in; "/>
											<td style="background-color:white; width:2.80in; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingSupplierParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PostalAddress">
																	<xsl:for-each select="cbc:PostalZone">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
												<span>
													<xsl:text>&#160;</xsl:text>
												</span>
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:AccountingSupplierParty">
															<xsl:for-each select="cac:Party">
																<xsl:for-each select="cac:PostalAddress">
																	<xsl:for-each select="cbc:CityName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="background-color:white; width:3in; "/>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr style="background-color:yellow; height:0.07in; ">
							<td>
								<span style="background-color:yellow; font-size:smaller; font-weight:lighter; ">
									<xsl:text>&#160;</xsl:text>
								</span>
								<span style="background-color:yellow; font-size:small; font-weight:lighter; ">
									<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
								</span>
							</td>
						</tr>
						<tr style="background-color:white; ">
							<td>
								<table border="0" width="100%">
									<xsl:variable name="altova:CurrContextGrid_0D9332B0" select="."/>
									<tbody>
										<tr style="height:1px; ">
											<td style="width:43px; ">
												<span>
													<xsl:text>&#160;</xsl:text>
												</span>
											</td>
											<td style="width:500px; ">
												<span style="background-color:white; ">
													<xsl:text>Kundeidentifikasjon (KID)&#160;&#160; </xsl:text>
												</span>
											</td>
											<td style="width:790px; ">
												<span style="background-color:white; ">
													<xsl:text>Kroner</xsl:text>
												</span>
											</td>
											<td style="width:940px; ">
												<span style="background-color:white; ">
													<xsl:text>Til konto</xsl:text>
												</span>
											</td>
										</tr>
										<tr style="height:1px; ">
											<td style="width:43px; "/>
											<td style="width:500px; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:PaymentMeans">
															<xsl:for-each select="cbc:PaymentID">
																<xsl:apply-templates/>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="width:790px; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:LegalMonetaryTotal">
															<xsl:for-each select="cbc:PayableAmount">
																<span>
																	<xsl:variable name="altova:seqContentStrings">
																		<xsl:value-of select="format-number(number(string(.)), '### ##0,00', 'format1')"/>
																	</xsl:variable>
																	<xsl:variable name="sContent" select="string($altova:seqContentStrings)"/>
																	<xsl:value-of select="$sContent"/>
																</span>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
											<td style="width:940px; ">
												<xsl:for-each select="$XML">
													<xsl:for-each select="n1:Invoice">
														<xsl:for-each select="cac:PaymentMeans">
															<xsl:for-each select="cac:PayeeFinancialAccount">
																<xsl:for-each select="cbc:ID">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</xsl:for-each>
														</xsl:for-each>
													</xsl:for-each>
												</xsl:for-each>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr style="background-color:yellow; height:0.13in; ">
							<td/>
						</tr>
					</tbody>
				</table>
				<br/>
				<br/>
				<br/>
				<br/>
				<br/>
				<span style="background-color:white; font-size:small; ">
					<xsl:text>&#160;</xsl:text>
				</span>
				<span style="font-size:small; ">
					<xsl:text>&#160;</xsl:text>
				</span>
				<xsl:for-each select="$XML"/>
				<br/>
				<span style="font-family:Arial; font-size:small; ">
					<xsl:text>&#160;</xsl:text>
				</span>
				<br/>
				<br/>
				<br/>
				<br/>
				<span style="font-size:small; text-align:right; ">
					<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
				</span>
				<br/>
				<span style="font-size:small; text-align:right; ">
					<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
				</span>
				<br/>
				<br/>
				<span style="font-size:small; ">
					<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
				</span>
				<br/>
				<br/>
				<span style="font-size:small; ">
					<xsl:text>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160; </xsl:text>
				</span>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
